version: '2.1'
services:
  postgresql:
    image: postgres:11
    volumes:
      - 'postgresql_data:/postgresql'
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  pgbouncer:
    image: docker.io/bitnami/pgbouncer:latest
    ports:
      - 6543:6432
    environment:
      - POSTGRESQL_HOST=postgresql
      - PGBOUNCER_AUTH_TYPE=trust
      - PGBOUNCER_STATS_USERS=pgbouncer
      - PGBOUNCER_IGNORE_STARTUP_PARAMETERS=extra_float_digits
volumes:
  postgresql_data:
    driver: local
